### PR TITLE
Merge chromeos-5.4 into master

### PR DESCRIPTION
**Pull request by Pobega**

### CODE REVIEW

**Comment by Pobega** [comment]
@jefferymiller I know there's not much you can say about this PR, but I wanted to ask if you think I should autopick this over to 86 or just do another manual merge over there? I imagine the branches are pretty similar.

**Comment by nicholasbishop** [comment]
I wouldn't use autopick for this, just merge it to the other branch

**Comment by Pobega** [comment]
@nicholasbishop That's what I assumed, thanks

**Review by jefferymiller — APPROVED** [review]

**Comment by jefferymiller** [comment]
Don't autopick the merge. Just do the merge on those branches.

**Pull request merged**
