### PR TITLE
neverware: Add ThinkPad X1 Carbon Gen 8 to sof allow list.

### PR DESCRIPTION
**Pull request by eshiman**
OVER-13396

### CODE REVIEW

**Review by jefferymiller — APPROVED** [review]
lgtm

**Comment by eshiman** [comment]
There was some odd docker error so I resolved that by adding more details to the commit message, causing it to rebuild

**Comment by eshiman** [comment]
autopick: master, 88

**Comment by eshiman** [comment]
autopick: master neverware-d88

**Pull request merged**
